### ISSUE TITLE
github 'actions' CI error, but local is successed

### ISSUE THREAD

**Issue by liuziyuan** [quarkiverse/quarkiverse-devops#256]
When github CI , the UT has error , but at local ,i used mvn package, the UT is right.

this is my last build CI link, https://github.com/quarkiverse/quarkus-easy-retrofit/actions/runs/10242372364

this is the github CI log.  This issue seems to be related to Graalvm's dynamic proxy, but why doesn't my local Oracle Graalvm have this problem
```
========================================================================================================================
GraalVM Native Image: Generating 'quarkus-easy-retrofit-integration-tests-1.0.0-runner' (executable)...
========================================================================================================================
For detailed information and explanations on the build output, visit:
https://github.com/oracle/graal/blob/master/docs/reference-manual/native-image/BuildOutput.md
------------------------------------------------------------------------------------------------------------------------
[1/8] Initializing...                                                                                    (7.2s @ 0.16GB)
 Java version: 21.0.4+7-LTS, vendor version: Mandrel-23.1.4.0-Final
 Graal compiler: optimization level: 2, target machine: x86-64-v3
 C compiler: gcc (redhat, x86_64, 8.5.0)
 Garbage collector: Serial GC (max heap size: 80% of RAM)
 3 user-specific feature(s):
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase
------------------------------------------------------------------------------------------------------------------------
 4 experimental option(s) unlocked:
 - '-H:+AllowFoldMethods' (origin(s): command line)
 - '-H:BuildOutputJSONFile' (origin(s): command line)
 - '-H:-UseServiceLoaderFeature' (origin(s): command line)
 - '-H:+GenerateBuildArtifactsFile' (origin(s): command line)
------------------------------------------------------------------------------------------------------------------------
Build resources:
 - 9.76GB of memory (62.6% of 15.61GB system memory, determined at start)
 - 4 thread(s) (100.0% of 4 available processor(s), determined at start)
[2/8] Performing analysis...  [******]                                                                  (53.5s @ 1.40GB)
   14,679 reachable types   (88.1% of   16,656 total)
   20,561 reachable fields  (57.8% of   35,545 total)
   74,554 reachable methods (57.4% of  129,813 total)
    4,658 types,   179 fields, and 3,560 methods registered for reflection
       62 types,    67 fields, and    55 methods registered for JNI access
        4 native libraries: dl, pthread, rt, z
[3/8] Building universe...                                                                               (8.7s @ 1.29GB)
[4/8] Parsing methods...      [***]                                                                      (5.6s @ 1.44GB)
[5/8] Inlining methods...     [***]                                                                      (3.7s @ 1.57GB)
[6/8] Compiling methods...    [*******]                                                                 (48.4s @ 1.14GB)
[7/8] Layouting methods...    [**]                                                                       (4.5s @ 1.59GB)
[8/8] Creating image...       [***]                                                                      (7.2s @ 1.11GB)
  29.67MB (45.69%) for code area:    47,509 compilation units
  34.88MB (53.70%) for image heap:  400,152 objects and 86 resources
 407.30kB ( 0.61%) for other data
  64.94MB in total
------------------------------------------------------------------------------------------------------------------------
Top 10 origins of code area:                                Top 10 object types in image heap:
  12.69MB java.base                                            9.55MB byte[] for code metadata
   3.31MB org.jetbrains.kotlin.kotlin-reflect-2.0.0.jar        5.41MB byte[] for java.lang.String
   1.77MB c.f.jackson.core.jackson-databind-2.17.2.jar         3.70MB java.lang.Class
   1.31MB svm.jar (Native Image)                               3.44MB java.lang.String
   1.15MB q.0.0-runner.jar                                     1.23MB com.oracle.svm.core.hub.DynamicHubCompanion
 929.94kB modified-io.vertx.vertx-core-4.5.8.jar               1.13MB byte[] for general heap data
 573.00kB com.fasterxml.jackson.core.jackson-core-2.17.2.jar 914.40kB byte[] for reflection metadata
 569.18kB io.netty.netty-buffer-4.1.111.Final.jar            888.21kB java.lang.Object[]
 508.79kB io.netty.netty-common-4.1.111.Final.jar            687.48kB java.lang.String[]
 484.05kB com.squareup.okhttp3.okhttp-3.14.9.jar             527.15kB c.o.svm.core.hub.DynamicHub$ReflectionMetadata
   6.10MB for 95 more packages                                 7.47MB for 3765 more object types
------------------------------------------------------------------------------------------------------------------------
Recommendations:
 HEAP: Set max heap for improved and more predictable memory usage.
 CPU:  Enable more CPU features with '-march=native' for improved performance.
------------------------------------------------------------------------------------------------------------------------
                      14.6s (10.4% of total time) in 1616 GCs | Peak RSS: 2.58GB | CPU load: 3.60
------------------------------------------------------------------------------------------------------------------------
Produced artifacts:
 /project/build-artifacts.json (build_info)
 /project/quarkus-easy-retrofit-integration-tests-1.0.0-runner (executable)
 /project/quarkus-easy-retrofit-integration-tests-1.0.0-runner-build-output-stats.json (build_info)
========================================================================================================================
Finished generating 'quarkus-easy-retrofit-integration-tests-1.0.0-runner' in 2m 19s.
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] docker run --env LANG=C --rm --user 1001:127 -v /home/runner/work/quarkus-easy-retrofit/quarkus-easy-retrofit/integration-tests/target/quarkus-easy-retrofit-integration-tests-1.0.0-native-image-source-jar:/project:z --entrypoint /bin/bash quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21 -c objcopy --strip-debug quarkus-easy-retrofit-integration-tests-1.0.0-runner
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 157953ms
[INFO] 
[INFO] --- maven-failsafe-plugin:3.2.5:integration-test (default) @ quarkus-easy-retrofit-integration-tests ---
[INFO] Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkiverse.quarkus.easy.retrofit.it.EasyRetrofitResourceIT
Executing "/home/runner/work/quarkus-easy-retrofit/quarkus-easy-retrofit/integration-tests/target/quarkus-easy-retrofit-integration-tests-1.0.0-runner -Dquarkus.http.port=8081 -Dquarkus.http.ssl-port=8444 -Dtest.url=http://localhost:8081 -Dquarkus.log.file.path=/home/runner/work/quarkus-easy-retrofit/quarkus-easy-retrofit/integration-tests/target/quarkus.log -Dquarkus.log.file.enable=true -Dquarkus.log.category."io.quarkus".level=INFO -Dquarkus.native.container-build=true"
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2024-08-05 04:06:45,770 ERROR [io.qua.run.Application] (main) Failed to start application: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: org.graalvm.nativeimage.MissingReflectionRegistrationError: The program tried to reflectively access the proxy class inheriting [io.quarkiverse.quarkus.easy.retrofit.it.api.BaseApi] without it being registered for runtime reflection. Add [io.quarkiverse.quarkus.easy.retrofit.it.api.BaseApi] to the dynamic-proxy metadata to solve this problem. Note: The order of interfaces used to create proxies matters. See https://www.graalvm.org/latest/reference-manual/native-image/metadata/#dynamic-proxy for help.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.MissingReflectionRegistrationUtils.forProxy(MissingReflectionRegistrationUtils.java:89)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.proxy.DynamicProxySupport.getProxyClass(DynamicProxySupport.java:176)
	at java.base@21.0.4/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:47)
	at java.base@21.0.4/java.lang.reflect.Proxy.newProxyInstance(Proxy.java:1034)
	at retrofit2.Retrofit.create(Retrofit.java:160)
	at io.quarkiverse.quarkus.easy.retrofit.runtime.RetrofitApiServiceProxyRecorderRegister.build(RetrofitApiServiceProxyRecorderRegister.java:43)
	at io.quarkiverse.quarkus.easy.retrofit.runtime.RetrofitRecorder.getRetrofitApiInstance(RetrofitRecorder.java:32)
	at io.quarkus.deployment.steps.EasyRetrofitProcessor$registerRetrofitResource447346207.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.EasyRetrofitProcessor$registerRetrofitResource447346207.deploy(Unknown Source)
	... 7 more

Failed to launch the application. The application logs can be found at: /home/runner/work/quarkus-easy-retrofit/quarkus-easy-retrofit/integration-tests/target/quarkus.log
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.513 s <<< FAILURE! -- in io.quarkiverse.quarkus.easy.retrofit.it.EasyRetrofitResourceIT
Error:  io.quarkiverse.quarkus.easy.retrofit.it.EasyRetrofitResourceIT.testHelloEndpoint -- Time elapsed: 0.012 s <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: Unable to successfully launch process '3184'. Exit code is: '1'.
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.throwBootFailureException(QuarkusIntegrationTestExtension.java:375)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeEach(QuarkusIntegrationTestExtension.java:118)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.RuntimeException: Unable to successfully launch process '3184'. Exit code is: '1'.
	at io.quarkus.test.common.LauncherUtil.ensureProcessIsAlive(LauncherUtil.java:124)
	at io.quarkus.test.common.LauncherUtil.waitForCapturedListeningData(LauncherUtil.java:87)
	at io.quarkus.test.common.DefaultNativeImageLauncher.start(DefaultNativeImageLauncher.java:110)
	at io.quarkus.test.junit.IntegrationTestUtil.startLauncher(IntegrationTestUtil.java:194)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.doProcessStart(QuarkusIntegrationTestExtension.java:303)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.ensureStarted(QuarkusIntegrationTestExtension.java:170)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeAll(QuarkusIntegrationTestExtension.java:131)
	... 1 more

[INFO] 
[INFO] Results:
[INFO] 
Error:  Errors: 
Error:    EasyRetrofitResourceIT.testHelloEndpoint » Runtime java.lang.RuntimeException: Unable to successfully launch process '3184'. Exit code is: '1'.
[INFO] 
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- maven-failsafe-plugin:3.2.5:verify (default) @ quarkus-easy-retrofit-integration-tests ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Quarkus Easy Retrofit - Parent 1.0.0:
[INFO] 
[INFO] Quarkus Easy Retrofit - Parent ..................... SUCCESS [  0.950 s]
[INFO] Quarkus Easy Retrofit - Runtime .................... SUCCESS [  2.[364](https://github.com/quarkiverse/quarkus-easy-retrofit/actions/runs/10242372364/job/28331992824#step:6:365) s]
[INFO] Quarkus Easy Retrofit - Deployment ................. SUCCESS [  6.265 s]
[INFO] Quarkus Easy Retrofit - Documentation .............. SUCCESS [  5.570 s]
[INFO] Quarkus Easy Retrofit - Integration Tests .......... FAILURE [02:42 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:58 min
[INFO] Finished at: 2024-08-05T04:06:45Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:3.2.5:verify (default) on project quarkus-easy-retrofit-integration-tests: 
Error:  
Error:  Please refer to /home/runner/work/quarkus-easy-retrofit/quarkus-easy-retrofit/integration-tests/target/failsafe-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :quarkus-easy-retrofit-integration-tests
Error: Process completed with exit code 1.
```

and , this is my local ut log.
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.quarkiverse.quarkus.easy.retrofit.it.EasyRetrofitResourceTest
2024-08-05 12:00:47,979 DEBUG [io.git.liu.ret.cor.RetrofitResourceScanner] (build-2) Scanner Pattern : .*?(io/quarkiverse/quarkus/easy/retrofit/it).*?
2024-08-05 12:00:47,985 DEBUG [io.git.liu.ret.cor.RetrofitResourceScanner] (build-2) Filter inputs io/quarkiverse/quarkus/easy/retrofit/it/EasyRetrofitResourceTest.class
2024-08-05 12:00:47,985 DEBUG [io.git.liu.ret.cor.RetrofitResourceScanner] (ForkJoinPool.commonPool-worker-4) Filter inputs io/quarkiverse/quarkus/easy/retrofit/it/BackendApiResource.class
2024-08-05 12:00:47,992 DEBUG [io.git.liu.ret.cor.RetrofitResourceScanner] (build-2) Filter inputs io/quarkiverse/quarkus/easy/retrofit/it/EasyRetrofitResourceIT.class
2024-08-05 12:00:47,992 DEBUG [io.git.liu.ret.cor.RetrofitResourceScanner] (ForkJoinPool.commonPool-worker-4) Filter inputs io/quarkiverse/quarkus/easy/retrofit/it/api/BaseApi.class
2024-08-05 12:00:47,992 DEBUG [io.git.liu.ret.cor.RetrofitResourceScanner] (build-2) Filter inputs EasyRetrofitResourceTest.idx
2024-08-05 12:00:47,992 DEBUG [io.git.liu.ret.cor.RetrofitResourceScanner] (build-2) Filter inputs EasyRetrofitResourceTest.idx
2024-08-05 12:00:47,993 DEBUG [io.git.liu.ret.cor.RetrofitResourceScanner] (ForkJoinPool.commonPool-worker-4) Filter inputs io/quarkiverse/quarkus/easy/retrofit/it/api/retrofit/BodyCallAdapterFactoryBuilder.class
2024-08-05 12:00:47,993 DEBUG [io.git.liu.ret.cor.RetrofitResourceScanner] (ForkJoinPool.commonPool-worker-4) Filter inputs io/quarkiverse/quarkus/easy/retrofit/it/api/retrofit/JacksonConvertFactoryBuilder.class
2024-08-05 12:00:47,993 DEBUG [io.git.liu.ret.cor.RetrofitResourceScanner] (ForkJoinPool.commonPool-worker-4) Filter inputs io/quarkiverse/quarkus/easy/retrofit/it/api/retrofit/GuavaCallAdapterFactoryBuilder.class
2024-08-05 12:00:47,993 DEBUG [io.git.liu.ret.cor.RetrofitResourceScanner] (ForkJoinPool.commonPool-worker-4) Filter inputs io/quarkiverse/quarkus/easy/retrofit/it/EasyRetrofitResource.class
2024-08-05 12:00:47,994 DEBUG [io.git.liu.ret.cor.RetrofitResourceScanner] (ForkJoinPool.commonPool-worker-4) Filter inputs application.properties
2024-08-05 12:00:47,994 DEBUG [io.git.liu.ret.cor.RetrofitResourceScanner] (ForkJoinPool.commonPool-worker-4) Filter inputs application.properties
2024-08-05 12:00:47,995 INFO  [org.ref.Reflections] (build-2) Reflections took 12 ms to scan 2 urls, producing 9 keys and 15 values
2024-08-05 12:00:48,002 INFO  [org.ref.Reflections] (build-2) Reflections took 2 ms to scan 21 urls, producing 9 keys and 15 values
2024-08-05 12:00:48,009 INFO  [io.qua.qua.eas.ret.run.RetrofitLogoVersion] (build-29) 
__________        __                 _____.__  __   
\______   \ _____/  |________  _____/ ____\__|/  |_ 
 |       _// __ \   __\_  __ \/  _ \   __\|  \   __\
 |    |   \  ___/|  |  |  | \(  <_> )  |  |  ||  |  
 |____|_  /\___  >__|  |__|   \____/|__|  |__||__|  
        \/     \/                                   
::Quarkus Easy Retrofit Client ::          (null)
::Retrofit ::                              (v2.11.0)

2024-08-05 12:00:48,010 INFO  [io.git.liu.ret.cor.RetrofitResourceContextLog] (build-29) ---Retrofit Client : HostURL: http://localhost:8080/, Retrofit instance name: Retrofit@c99a5af90662a954bce7b140082226c3
2024-08-05 12:00:48,011 DEBUG [io.git.liu.ret.cor.RetrofitResourceContextLog] (build-29) RetrofitClientBean: HostURL: http://localhost:8080/; UrlStatus: DEFAULT_URL_ONLY; globalEnable: false; CallAdapterFactory: BodyCallAdapterFactoryBuilder,GuavaCallAdapterFactoryBuilder; ConverterFactory:JacksonConvertFactoryBuilder; callbackExecutor: BaseCallBackExecutorBuilder; client: BaseOkHttpClientBuilder; callFactory: BaseCallFactoryBuilder; validateEagerly: false; interceptor: []
2024-08-05 12:00:48,011 INFO  [io.git.liu.ret.cor.RetrofitResourceContextLog] (build-29) |--API Services: Interface name: io.quarkiverse.quarkus.easy.retrofit.it.api.BaseApi , Parent Interface name: null
2024-08-05 12:00:48,012 DEBUG [io.git.liu.ret.cor.RetrofitResourceContextLog] (build-29) RetrofitApiServiceBean{selfClazz=interface io.quarkiverse.quarkus.easy.retrofit.it.api.BaseApi, parentClazz=interface io.quarkiverse.quarkus.easy.retrofit.it.api.BaseApi, retrofitUrl=RetrofitUrl{inputDefaultBaseUrl='http://localhost:8080/', inputDynamicBaseUrl='null', defaultUrl=BaseUrl{realBaseUrl='http://localhost:8080/', realHostUrl='http://localhost:8080/', realPrefixUrl=''}, dynamicUrl=BaseUrl{realBaseUrl='', realHostUrl='', realPrefixUrl=''}, retrofitUrlPrefix='', urlStatus=DEFAULT_URL_ONLY}, retrofitBuilder=RetrofitBuilderBean{enable=false, overwriteType=GLOBAL_FIRST, baseUrl='${backend.base.url}', addCallAdapterFactory=io.quarkiverse.quarkus.easy.retrofit.it.api.retrofit.BodyCallAdapterFactoryBuilder,io.quarkiverse.quarkus.easy.retrofit.it.api.retrofit.GuavaCallAdapterFactoryBuilder, addConverterFactory=io.quarkiverse.quarkus.easy.retrofit.it.api.retrofit.JacksonConvertFactoryBuilder, client=class io.github.liuziyuan.retrofit.core.builder.BaseOkHttpClientBuilder, callbackExecutor=class io.github.liuziyuan.retrofit.core.builder.BaseCallBackExecutorBuilder, callFactory=class io.github.liuziyuan.retrofit.core.builder.BaseCallFactoryBuilder, validateEagerly=false}, interceptors=, myInterceptors=, exceptionDelegates=null}
2024-08-05 12:00:48,490 INFO  [io.quarkus] (main) quarkus-easy-retrofit-integration-tests 1.0.0 on JVM (powered by Quarkus 3.13.0) started in 0.952s. Listening on: http://localhost:8081
2024-08-05 12:00:48,491 INFO  [io.quarkus] (main) Profile test activated. 
2024-08-05 12:00:48,491 INFO  [io.quarkus] (main) Installed features: [cdi, easy-retrofit, kotlin, rest, smallrye-context-propagation, vertx]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.155 s -- in io.quarkiverse.quarkus.easy.retrofit.it.EasyRetrofitResourceTest
2024-08-05 12:00:48,821 INFO  [io.quarkus] (main) quarkus-easy-retrofit-integration-tests stopped in 0.010s
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- jar:3.3.0:jar (default-jar) @ quarkus-easy-retrofit-integration-tests ---
[INFO] Building jar: /Users/liuziyuan/work/home/java/workspace/quarkus/quarkus-easy-retrofit/integration-tests/target/quarkus-easy-retrofit-integration-tests-1.0.0.jar
[INFO] 
[INFO] --- source:3.3.0:jar-no-fork (attach-sources) @ quarkus-easy-retrofit-integration-tests ---
[INFO] Building jar: /Users/liuziyuan/work/home/java/workspace/quarkus/quarkus-easy-retrofit/integration-tests/target/quarkus-easy-retrofit-integration-tests-1.0.0-sources.jar
[INFO] 
[INFO] --- quarkus:3.13.0:build (default) @ quarkus-easy-retrofit-integration-tests ---
[INFO] Reflections took 11 ms to scan 1 urls, producing 6 keys and 12 values
[INFO] Reflections took 2 ms to scan 9 urls, producing 0 keys and 0 values
[INFO] [io.quarkiverse.quarkus.easy.retrofit.runtime.RetrofitLogoVersion] 
__________        __                 _____.__  __   
\______   \ _____/  |________  _____/ ____\__|/  |_ 
 |       _// __ \   __\_  __ \/  _ \   __\|  \   __\
 |    |   \  ___/|  |  |  | \(  <_> )  |  |  ||  |  
 |____|_  /\___  >__|  |__|   \____/|__|  |__||__|  
        \/     \/                                   
::Quarkus Easy Retrofit Client ::          (1.0.0)
::Retrofit ::                              (v2.11.0)

[INFO] ---Retrofit Client : HostURL: http://localhost:8080/, Retrofit instance name: Retrofit@c99a5af90662a954bce7b140082226c3
[INFO] |--API Services: Interface name: io.quarkiverse.quarkus.easy.retrofit.it.api.BaseApi , Parent Interface name: null
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 524ms
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Quarkus Easy Retrofit - Parent 1.0.0:
[INFO] 
[INFO] Quarkus Easy Retrofit - Parent ..................... SUCCESS [  0.516 s]
[INFO] Quarkus Easy Retrofit - Runtime .................... SUCCESS [  1.711 s]
[INFO] Quarkus Easy Retrofit - Deployment ................. SUCCESS [  2.684 s]
[INFO] Quarkus Easy Retrofit - Documentation .............. SUCCESS [  2.297 s]
[INFO] Quarkus Easy Retrofit - Integration Tests .......... SUCCESS [  3.627 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.902 s
[INFO] Finished at: 2024-08-05T12:00:49+08:00
[INFO] ------------------------------------------------------------------------

```

**Comment by liuziyuan** [comment]
I seem to have solved this problem. 
two options:
1. when use 3.13.0 ,we can add @RegisterForProxy annotation to interface which will be dynamic proxy 
2. add a NativeImageProxyDefinitionBuildItem BuildStep, get interface name and set to NativeImageProxyDefinitionBuildItem object
